packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - nx
  - prisma
  - sharp
